services:
    notification-service:
        build:
            context: ./notification-service
        ports:
            - 5000:5000
        networks:
            - alon-network
    order-service:
        build:
            context: ./order-service
        ports:
            - 5001:5001
        networks:
            - alon-network
    payment-service:
        build:
            context: ./payment-service
        ports:
            - 5002:5002
        networks:
            - alon-network
    product-service:
        build:
            context: ./product-service
        ports:
            - 5003:5003
        networks:
            - alon-network
    shopping-cart-service:
        build:
            context: ./shopping-cart-service
        ports:
            - 5004:5004
        networks:
            - alon-network
    user-service:
        build:
            context: ./user-service
        ports:
            - $USER_PORT:$USER_PORT
        networks:
            - alon-network
        depends_on:
            - mongo
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - USER_PORT=${USER_PORT}

    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db
        networks:
            - alon-network

    redis:
        image: redis:alpine
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        networks:
          - alon-network

volumes:
    mongo:

networks:
    alon-network:
